import 'package:flutter/material.dart';
import 'package:provider/provider.dart';


import '../main.dart';
import '../models/user.dart';
import '../providers/user_provider.dart';

class CreateNewUser extends StatefulWidget {
  const CreateNewUser({super.key});

  @override
  CreateNewUserState createState() => CreateNewUserState();
}

class CreateNewUserState extends State<CreateNewUser> {
  final _formKey = GlobalKey<FormState>();

  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _streetController = TextEditingController();
  final _suiteController = TextEditingController();
  final _cityController = TextEditingController();
  final _zipcodeController = TextEditingController();
  final _latController = TextEditingController();
  final _lngController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _streetController.dispose();
    _suiteController.dispose();
    _cityController.dispose();
    _zipcodeController.dispose();
    _latController.dispose();
    _lngController.dispose();
    super.dispose();
  }

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      final newUser = User(
        id: 0,
        // Assuming the ID is generated by the backend
        name: _nameController.text,
        email: _emailController.text,
        phone: _phoneController.text,
        address: Address(
          street: _streetController.text,
          suite: _suiteController.text,
          city: _cityController.text,
          zipcode: _zipcodeController.text,
          geo: Geo(
            lat: _latController.text,
            lng: _lngController.text,
          ),
        ),
      );

      Provider.of<UserProvider>(context, listen: false).addUser(newUser);

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('User Added Successfully!'),
            backgroundColor: Colors.green,
            // behavior: SnackBarBehavior.floating,
          ),
        );
      }

      Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Creating a New User'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Name'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a name';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _emailController,
                decoration: const InputDecoration(labelText: 'Email'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an email';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _phoneController,
                decoration: const InputDecoration(labelText: 'Phone'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a phone number';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _streetController,
                decoration: const InputDecoration(labelText: 'Street'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a street';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _suiteController,
                decoration: const InputDecoration(labelText: 'Suite'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a suite';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _cityController,
                decoration: const InputDecoration(labelText: 'City'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a city';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _zipcodeController,
                decoration: const InputDecoration(labelText: 'Zipcode'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a zipcode';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _latController,
                decoration: const InputDecoration(labelText: 'Latitude'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a latitude';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _lngController,
                decoration: const InputDecoration(labelText: 'Longitude'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a longitude';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitForm,
                child: const Text(
                  'Create User',
                  style: TextStyle(color: primaryTextColor),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
